# Define services for Asgard
# TODO: add health checks, restart policies and extract hardcoded ports/tags/etc. to .env files
version: "3.8"

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  ############ QUETZALCOATL ############

  quetzalcoatl-auth-api:
    container_name: quetzalcoatl-auth-api
    image: quetzalcoatl-auth:1.0
    build:
      context: quetzalcoatl-auth
      dockerfile: ../quetzalcoatl-auth/Dockerfile
    ports:
      - "5210:5210"
    env_file:
      - quetzalcoatl-auth/.env
    restart: always
    depends_on:
      quetzalcoatl-mssql-db:
        condition: service_started
    profiles:
      - quetzalcoatl

  quetzalcoatl-auth-dapr:
    container_name: quetzalcoatl-auth-dapr
    image: daprio/daprd:1.11.2
    command:
      [
        "./daprd",
        "-app-id",
        "quetzalcoatl-auth",
        "-app-port",
        "5210",
        "-placement-host-address",
        "asgard-dapr-placement:40000",
        "-dapr-http-port",
        "3500",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - asgard-dapr-config
    depends_on:
      - quetzalcoatl-auth-api
    network_mode: "service:quetzalcoatl-auth-api"
    profiles:
      - quetzalcoatl

  quetzalcoatl-mssql-db:
    container_name: quetzalcoatl-mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    user: root
    ports:
      - "1434:1433"
    env_file:
      - quetzalcoatl-auth/.env
    volumes:
      - quetzalcoatl-db:/var/opt/mssql/data
    profiles:
      - quetzalcoatl

  ############ ENKI ############

  enki-problems-api:
    container_name: enki-problems-api
    image: enki-problems:1.0
    build:
      context: enki-problems
      dockerfile: ../enki-problems/Dockerfile
    ports:
      - "5211:5211"
    env_file:
      - enki-problems/.env
    restart: always
    depends_on:
      enki-mongo-db:
        condition: service_started
      asgard-redis:
        condition: service_started
      hermes-tests-api:
        condition: service_started
      hermes-tests-dapr:
        condition: service_started
    profiles:
      - enki

  enki-problems-dapr:
    container_name: enki-problems-dapr
    image: daprio/daprd:1.11.2
    command:
      [
        "./daprd",
        "-app-id",
        "enki-problems",
        "-app-port",
        "5211",
        "-placement-host-address",
        "asgard-dapr-placement:40000",
        "-dapr-http-port",
        "3501",
        "-dapr-grpc-port",
        "50001",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - asgard-dapr-config
    depends_on:
      - enki-problems-api
    network_mode: "service:enki-problems-api"
    profiles:
      - enki

  enki-mongo-db:
    container_name: enki-mongo-db
    image: mongo:5.0
    restart: always
    command: ["--replSet", "enki-rs", "--bind_ip_all", "--port", "30001"]
    volumes:
      - enki-db:/data/db
    ports:
      - 30001:30001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongo --port 30001 --quiet --eval "rs.initiate({_id:''enki-rs'',members:[{_id:0,host:"enki-mongo-db:30001"}]}).ok || rs.status().ok"',
        ]
      # test: test $(echo "rs.initiate({_id:'enki-rs',members:[{_id:0,host:\"enki-mongo-db:30001\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 3
    profiles:
      - enki

  ############ HERMES ############

  hermes-tests-api:
    container_name: hermes-tests-api
    image: hermes-tests:1.0
    build:
      context: hermes-tests
      dockerfile: ../hermes-tests/Dockerfile
    ports:
      - "5212:5212"
    env_file:
      - hermes-tests/.env
    restart: always
    profiles:
      - hermes

  hermes-tests-dapr:
    container_name: hermes-tests-dapr
    image: daprio/daprd:1.11.2
    command:
      [
        "./daprd",
        "-app-id",
        "hermes-tests",
        "-app-port",
        "5212",
        "-placement-host-address",
        "asgard-dapr-placement:40000",
        "-dapr-grpc-port",
        "50002",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - asgard-dapr-config
    depends_on:
      - hermes-tests-api
    network_mode: "service:hermes-tests-api"
    profiles:
      - hermes

  ############ ANUBIS ############

  anubis-eval-api:
    container_name: anubis-eval-api
    image: anubis-eval:1.0
    build:
      context: anubis-eval
      dockerfile: ../anubis-eval/Dockerfile
    ports:
      - "5213:5213"
    env_file:
      - anubis-eval/.env
    restart: always
    # profiles:
    #   - anubis

  anubis-eval-dapr:
    container_name: anubis-eval-dapr
    image: daprio/daprd:1.11.2
    command:
      [
        "./daprd",
        "-app-id",
        "anubis-eval",
        "-app-port",
        "5213",
        "-placement-host-address",
        "asgard-dapr-placement:40000",
        "-dapr-http-port",
        "3503",
        "-dapr-grpc-port",
        "50003",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - asgard-dapr-config
    ports:
      - "3503:3503"
    # depends_on:
    #   - anubis-eval-api
    # network_mode: "service:anubis-eval-api"
    profiles:
      - anubis

  anubis-psql-db:
    container_name: anubis-psql-db
    image: postgres:14.1
    volumes:
      - anubis-db:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - anubis-eval/.env
    profiles:
      - anubis

  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./anubis-eval/.env.judge0:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    profiles:
      - anubis

  judge0-server-dapr:
    container_name: judge0-server-dapr
    image: daprio/daprd:1.11.2
    command:
      [
        "./daprd",
        "-app-id",
        "judge0-server",
        "-app-port",
        "2358",
        "-placement-host-address",
        "asgard-dapr-placement:40000",
        "-dapr-http-port",
        "3504",
        "-dapr-grpc-port",
        "50004",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes_from:
      - asgard-dapr-config
    depends_on:
      - server
    network_mode: "service:server"
    profiles:
      - anubis

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./anubis-eval/.env.judge0:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    profiles:
      - anubis

  db:
    image: postgres:13.0
    env_file: ./anubis-eval/.env.judge0
    volumes:
      - judge0-db:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    profiles:
      - anubis

  redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: ./anubis-eval/.env.judge0
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always
    profiles:
      - anubis

  ############ DAPR ############

  asgard-dapr-placement:
    container_name: asgard-dapr-placement
    image: daprio/placement:1.11.2
    command: ["./placement", "-port", "40000", "-log-level", "debug"]
    ports:
      - "40000"
    profiles:
      - dapr

  asgard-redis:
    container_name: asgard-redis
    image: redis:alpine
    ports:
      - "6379"
    profiles:
      - dapr

  asgard-zipkin:
    container_name: asgard-zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "19411:9411"
    profiles:
      - dapr

  asgard-dapr-config:
    container_name: asgard-dapr-config
    image: asgard-dapr-config:1.0
    build:
      context: ./dapr
      dockerfile: Dockerfile
    profiles:
      - dapr

  ############ VOLUMES ############

volumes:
  quetzalcoatl-db:
    driver: local
  enki-db:
    driver: local
  anubis-db:
    driver: local
  judge0-db:
    driver: local
  redis-data:
    driver: local

  ############ NETWORKS ############

networks:
  default:
    name: asgard-network
    driver: bridge
