# Define services for Asgard
# TODO: add health checks, restart policies and extract hardcoded ports/tags/etc. to .env files

services:
  ############ ODIN ############

  odin-api-gateway:
    container_name: odin-api-gateway
    image: ${REGISTRY:-ghcr.io/pantheonix}/odin-api-gateway:${TAG:-develop}
    env_file:
      - envs/.env.odin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./envs/certs/asgard/https.crt:/etc/ssl/certs/https.crt
      - ./envs/certs/asgard/key.pem:/etc/ssl/certs/key.pem
    restart: unless-stopped

  ############ QUETZALCOATL ############

  quetzalcoatl-auth-api:
    container_name: quetzalcoatl-auth-api
    image: ${REGISTRY:-ghcr.io/pantheonix}/quetzalcoatl-auth:${TAG:-develop}
    ports:
      - "80"
    env_file:
      - envs/.env.quetzalcoatl
    restart: unless-stopped

  ############ ENKI ############

  enki-problems-api:
    container_name: enki-problems-api
    image: ${REGISTRY:-ghcr.io/pantheonix}/enki-problems:${TAG:-develop}
    ports:
      - "80"
    env_file:
      - envs/.env.enki
    restart: unless-stopped

  ############ HERMES ############

  hermes-tests-api:
    container_name: hermes-tests-api
    image: ${REGISTRY:-ghcr.io/pantheonix}/hermes-tests:${TAG:-develop}
    ports:
      - "80"
    env_file:
      - envs/.env.hermes
    restart: unless-stopped

  ############ ANUBIS ############

  anubis-eval-api:
    container_name: anubis-eval-api
    image: ${REGISTRY:-ghcr.io/pantheonix}/anubis-eval:${TAG:-develop}
    ports:
      - "80"
    env_file:
      - envs/.env.anubis
    restart: unless-stopped

  ############ VOLUMES ############

volumes:
  quetzalcoatl-db:
    driver: local
  enki-db:
    driver: local
  anubis-db:
    driver: local
  judge0-db:
    driver: local
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local
  dapr-redis-data:
    driver: local

  ############ NETWORKS ############

networks:
  default:
    name: asgard-network
    driver: bridge
