[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(anubis-eval)'
platform = 'cfg(unix)'
test-group = 'serial-integration'

[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false