repositories:
  - name: dapr
    url: https://dapr.github.io/helm-charts/

releases:
#  - name: dapr-crds
#    namespace: dapr-system
#    createNamespace: true
#    chart: dapr/dapr
#    version: 1.14
#    wait: true
#    values:
#      - global:
#          installCRDs: true
#    hooks:
#      - events: ["prepare"]
#        showlogs: true
#        command: "sh"
#        args: ["-c", "helm uninstall dapr-crds --namespace dapr-system || true"]

  - name: dapr
    namespace: dapr-system
    createNamespace: true
    chart: dapr/dapr
    version: 1.14
    wait: true
    force: true
    values:
      - global:
          installCRDs: true

  - name: dapr-dashboard
    namespace: dapr-system
    createNamespace: true
    chart: dapr/dapr-dashboard
    wait: true