repositories:
  - name: dapr
    url: https://dapr.github.io/helm-charts/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ot-container-kit
    url: https://ot-container-kit.github.io/helm-charts

# TODO: move operators to another namespace
releases:
  - name: dapr
    namespace: asgard
    chart: dapr/dapr
    version: 1.14
    wait: true
    values:
      - global:
          installCRDs: true

  - name: dapr-dashboard
    namespace: asgard
    chart: dapr/dapr-dashboard
    wait: true
    needs:
      - dapr

  - name: mongodb-operator
    namespace: asgard
    chart: ot-container-kit/mongodb-operator
    version: 0.3.1
    wait: true
    values:
      - global:
          installCRDs: true

  - name: rabbitmq-cluster-operator
    namespace: asgard
    chart: bitnami/rabbitmq-cluster-operator
    version: 4.3.29
    wait: true
    values:
      - global:
          installCRDs: true

  - name: asgard-local
    namespace: asgard
    chart: ./asgard-chart/
    needs:
      - dapr