global using NUnit.Framework;
global using Domain.Entities;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
global using Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using Tests.Core;
