name: hermes_tests
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  archive: ^3.3.6
  cron: ^0.5.1
#  firebase_core: ^1.19.0
  firebase_dart: ^1.0.11
#  firebase_storage: ^10.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  grpc: ^3.1.0
  injectable: ^2.1.0
  path: ^1.8.0
#  path_provider: ^2.0.12

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  lints: ^2.0.0
  test: ^1.21.0
