name: hermes_tests
description: Hermes Tests Microservice for uploading/downloading tests against
  Firebase Cloud Storage.
version: 1.0.0
repository: https://github.com/Pantheonix/Asgard
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  archive: ^3.3.6
  cqrs_mediator: ^0.1.1
  cron: ^0.5.1
  dartz: ^0.10.1
  firebase_dart: ^1.0.11
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  grpc: ^3.1.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  mocktail: ^0.3.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
