apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: allowedTopics # Optional
    value: "pending-submissions-topic,evaluated-submissions-topic"
  - name: publishingScopes # Optional
    value: "anubis-eval=evaluated-submissions-topic;thor-submissions=pending-submissions-topic;quetzalcoatl-auth=;enki-problems=;hermes-tests=;odin-gw="
  - name: subscriptionScopes # Optional
    value: "anubis-eval=pending-submissions-topic;thor-submissions=evaluated-submissions-topic;quetzalcoatl-auth=;enki-problems=;hermes-tests=;odin-gw="
scopes:
  - anubis-eval
  - thor-submissions
