apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: snssqs-pubsub
  namespace: asgard
spec:
  type: pubsub.aws.snssqs
  version: v1
  metadata:
    - name: accessKey
      secretKeyRef:
        name: Aws:AccessKey
        key: Aws:AccessKey
    - name: secretKey
      secretKeyRef:
        name: Aws:SecretKey
        key: Aws:SecretKey
    - name: region
      value: "eu-central-1"
    # - name: messageVisibilityTimeout # Optional
    #   value: 10
    # - name: messageRetryLimit # Optional
    #   value: 10
    # - name: messageReceiveLimit # Optional
    #   value: 10
    - name: sqsDeadLettersQueueName # Optional
    - value: "asgard-submissions-dlq"
    # - name: messageWaitTimeSeconds # Optional
    #   value: 1
    # - name: messageMaxNumber # Optional
    #   value: 10
    - name: disableEntityManagement # Optional
      value: "true"
    # - name: disableDeleteOnRetryLimit # Optional
    #   value: "false"
    # - name: assetsManagementTimeoutSeconds # Optional
    #   value: 5
    # - name: concurrencyMode # Optional
    #   value: "single"
    - name: allowedTopics # Optional
      value: "pending-submissions-topic,evaluated-submissions-topic"
    - name: publishingScopes # Optional
      value: "anubis-eval=evaluated-submissions-topic;thor-submission=pending-submissions-topic;quetzalcoatl-auth=;enki-problems=;hermes-tests=;odin-gw="
    - name: subscriptionScopes # Optional
      value: "anubis-eval=pending-submissions-topic;thor-submission=evaluated-submissions-topic;quetzalcoatl-auth=;enki-problems=;hermes-tests=;odin-gw="
auth:
  secretStore: asgard-secretstore
scopes:
- anubis-eval
- thor-submission