apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: asgard-secretstore
  namespace: asgard
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json
scopes:
- anubis-eval