apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservices.enki.name }}-db-password
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.microservices.enki.envs.MONGO_INITDB_ROOT_PASSWORD | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservices.enki.name }}-scram-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.microservices.enki.envs.MONGO_INITDB_ROOT_PASSWORD | quote }}

---

apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.microservices.enki.name }}-db
  namespace: {{ .Values.namespace }}
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.microservices.enki.envs.MONGO_INITDB_ROOT_USERNAME }}
      db: admin
      passwordSecretRef:
        name: {{ .Values.microservices.enki.name }}-db-password
      scramCredentialsSecretName: {{ .Values.microservices.enki.name }}-scram-credentials
      roles:
        - name: root
          db: {{ .Values.microservices.enki.envs.MONGO_INITDB_DATABASE }}