# TODO: refine the following StatefulSet definition to match enki requirements
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.enki.name }}-db-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.enki.name }}-db
spec:
  selector:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.enki.name }}-db
  ports:
    - port: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservices.enki.name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.enki.name }}-db
spec:
  serviceName: {{ .Values.microservices.enki.name }}-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      service: {{ .Values.microservices.enki.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.microservices.enki.name }}-db
    spec:
      containers:
        - name: {{ .Values.microservices.enki.name }}-db
          image: mongo:5.0
          startupProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
{{/*          env:*/}}
{{/*            - name: MONGO_INITDB_ROOT_USERNAME*/}}
{{/*              valueFrom:*/}}
{{/*                configMapKeyRef:*/}}
{{/*                  key: username*/}}
{{/*                  name: mongodb-config*/}}
{{/*            - name: MONGO_INITDB_ROOT_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  key: password*/}}
{{/*                  name: mongodb-secret*/}}
          command:
            - mongod
            - "--bind_ip_all"
            - --config=/etc/mongo/mongodb.conf
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /etc/mongo
      volumes:
        - name: mongodb-config
          configMap:
            name: mongodb-config
            items:
              - key: mongodb.conf
                path: mongodb.conf
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: demo-storage
        resources:
          requests:
            storage: 1Gi


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-storage  # Specifies the name of the StorageClass
provisioner: k8s.io/minikube-hostpath  # Specifies the provisioner used for volume provisioning
volumeBindingMode: Immediate  # Specifies that volumes should be immediately bound when requested
reclaimPolicy: Delete  # Specifies the reclaim policy for the volumes (Delete in this case)


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false
data:
  username: "admin1"
  mongodb.conf: |
    storage:
      dbPath: /data/db  # Sets the MongoDB data storage path
    replication:
      replSetName: "rs0"  # Specifies the name of the MongoDB replica set

---

{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: mongodb-secret*/}}
{{/*immutable: false*/}}
{{/*type: Opaque*/}}
{{/*data:*/}}
{{/*  password: password_for_mongodb*/}}
