apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.judge0.name }}-redis-svc
  namespace: {{ .Values.namespace }}
  labels:
      app: {{ .Values.microservices.judge0.name }}
      service: {{ .Values.microservices.judge0.name }}-redis
spec:
  selector:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}-redis
  ports:
    - port: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservices.judge0.name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.microservices.judge0.name }}
    service: {{ .Values.microservices.judge0.name }}-redis
spec:
  serviceName: {{ .Values.microservices.judge0.name }}-redis-svc
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.microservices.judge0.name }}
      service: {{ .Values.microservices.judge0.name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.microservices.judge0.name }}
        service: {{ .Values.microservices.judge0.name }}-redis
    spec:
      containers:
        - name: redis
          image: redis:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: {{ .Values.microservices.judge0.name }}-redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.microservices.judge0.name }}-redis-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.microservices.judge0.name }}-redis-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
