apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.microservices.judge0.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}
  ports:
    - name: http
      port: 80
      targetPort: judge0-http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.microservices.judge0.name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}
spec:
  replicas: {{ .Values.microservices.judge0.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      service: {{ .Values.microservices.judge0.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.microservices.judge0.name }}
    spec:
      containers:
        - name:  {{ .Values.microservices.judge0.name }}-api
          image: {{ template "judge0.image" . }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: judge0-http
              containerPort: 2358
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.microservices.judge0.name }}-cm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservices.judge0.name }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}
spec:
  replicas: {{ .Values.microservices.judge0.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      service: {{ .Values.microservices.judge0.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.microservices.judge0.name }}
    spec:
      containers:
        - name: {{ .Values.microservices.judge0.name }}-worker
          image: {{ template "judge0.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - bash
            - -c
            - while true; do rails resque:work; done
          envFrom:
            - configMapRef:
                name: {{ .Values.microservices.judge0.name }}-cm

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservices.judge0.name }}-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.judge0.name }}
data:
  RAILS_ENV: {{ .Values.RAILS_ENV | quote }}
  RAILS_MAX_THREADS: {{ .Values.RAILS_MAX_THREADS | quote }}
  SECRET_KEY_BASE: {{ .Values.SECRET_KEY_BASE | quote }}
  ALLOW_ORIGIN: {{ .Values.ALLOW_ORIGIN | quote }}
  AUTHN_HEADER: {{ .Values.AUTHN_HEADER | quote }}
  AUTHN_TOKEN: {{ .Values.AUTHN_TOKEN | quote }}
  AUTHZ_HEADER: {{ .Values.AUTHZ_HEADER | quote }}
  AUTHZ_TOKEN: {{ .Values.AUTHZ_TOKEN | quote }}
  INTERVAL: {{ .Values.INTERVAL | quote }}
  COUNT: {{ .Values.COUNT | quote }}
  REDIS_HOST: redis-svc
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  REDIS_PORT: {{ if .Values.redis.enabled }}{{ .Values.redis.redisPort | quote }}{{ else }}{{ .Values.external.redis.port | quote }}{{ end }}
  POSTGRES_HOST: {{ if .Values.postgresql.enabled }}{{ template "judge0.postgresql.fullname" . }}{{ else }}{{ .Values.external.postgresql.host | quote }}{{ end }}
  POSTGRES_DB: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.postgresqlDatabase | quote }}{{ else }}{{ .Values.external.postgresql.postgresqlDatabase | quote }}{{ end }}
  POSTGRES_USER: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.postgresqlUsername | quote }}{{ else }}{{ .Values.external.postgresql.postgresqlUsername | quote }}{{ end }}
  POSTGRES_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.postgresqlPassword | quote }}{{ else }}{{ .Values.external.postgresql.postgresqlPassword | quote }}{{ end }}
  POSTGRES_PORT: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.service.port | quote }}{{ else }}{{ .Values.external.postgresql.port | quote }}{{ end }}
  ENABLE_WAIT_RESULT: {{ .Values.ENABLE_WAIT_RESULT | quote }}
  CPU_TIME_LIMIT: {{ .Values.CPU_TIME_LIMIT | quote }}
  MAX_CPU_TIME_LIMIT: {{ .Values.MAX_CPU_TIME_LIMIT | quote }}
  CPU_EXTRA_TIME: {{ .Values.CPU_EXTRA_TIME | quote }}
  MAX_CPU_EXTRA_TIME: {{ .Values.MAX_CPU_EXTRA_TIME | quote }}
  WALL_TIME_LIMIT: {{ .Values.WALL_TIME_LIMIT | quote }}
  MAX_WALL_TIME_LIMIT: {{ .Values.MAX_WALL_TIME_LIMIT | quote }}
  MEMORY_LIMIT: {{ .Values.MEMORY_LIMIT | quote }}
  MAX_MEMORY_LIMIT: {{ .Values.MAX_MEMORY_LIMIT | quote }}
  MAX_STACK_LIMIT: {{ .Values.MAX_STACK_LIMIT | quote }}
  MAX_PROCESSES_AND_OR_THREADS: {{ .Values.MAX_PROCESSES_AND_OR_THREADS | quote }}
  MAX_MAX_PROCESSES_AND_OR_THREADS: {{ .Values.MAX_MAX_PROCESSES_AND_OR_THREADS | quote }}
  ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT: {{ .Values.ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT | quote }}
  ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT: {{ .Values.ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT | quote }}
  ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT: {{ .Values.ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT | quote }}
  ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT: {{ .Values.ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT | quote }}
  MAX_FILE_SIZE: {{ .Values.MAX_FILE_SIZE | quote }}
  MAX_MAX_FILE_SIZE: {{ .Values.MAX_MAX_FILE_SIZE | quote }}
  NUMBER_OF_RUNS: {{ .Values.NUMBER_OF_RUNS | quote }}
  MAX_NUMBER_OF_RUNS: {{ .Values.MAX_NUMBER_OF_RUNS | quote }}
  MAX_QUEUE_SIZE: {{ .Values.MAX_QUEUE_SIZE | quote }}
  DISALLOW_IP: {{ .Values.DISALLOW_IP | quote }}
  ALLOW_IP: {{ .Values.ALLOW_IP | quote }}
  DISALLOW_ORIGIN: {{ .Values.DISALLOW_ORIGIN | quote }}
  MAINTENANCE_MESSAGE: {{ .Values.MAINTENANCE_MESSAGE | quote }}
  MAINTENANCE_MODE: {{ .Values.MAINTENANCE_MODE | quote }}
