# TODO: refine the following StatefulSet definition to match quetzalcoatl requirements
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.quetzalcoatl.name }}-db-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.quetzalcoatl.name }}-db
spec:
  selector:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.quetzalcoatl.name }}-db
  ports:
    - port: 1433

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservices.quetzalcoatl.name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.quetzalcoatl.name }}-db
spec:
  serviceName: {{ .Values.microservices.quetzalcoatl.name }}-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      service: {{ .Values.microservices.quetzalcoatl.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.microservices.quetzalcoatl.name }}-db
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Values.microservices.quetzalcoatl.name }}-db
          image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          envFrom:
            - configMapRef:
                name: {{ .Values.microservices.quetzalcoatl.name }}-db-cm
            - secretRef:
                name: {{ .Values.microservices.quetzalcoatl.name }}-db-secret
          volumeMounts:
            - name: mssql
              mountPath: "/var/opt/mssql"
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservices.quetzalcoatl.name }}-db-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.quetzalcoatl.name }}-db
data:
  ACCEPT_EULA: {{ .Values.microservices.quetzalcoatl.envs.ACCEPT_EULA | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservices.quetzalcoatl.name }}-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.microservices.quetzalcoatl.name }}-db
data:
  SA_PASSWORD: {{ .Values.microservices.quetzalcoatl.envs.SA_PASSWORD | b64enc }}
