apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: {{ .Values.namespace }}
  labels:
      app: {{ .Values.microservices.judge0.name }}
      service: redis
spec:
  selector:
    app: {{ .Chart.Name }}
    service: redis
  ports:
    - port: 6379
      targetPort: redis-port

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}
    service: redis
spec:
  serviceName: redis-svc
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.namespace }}
      service: redis
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-port
              containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
