version: "3.8"

services:
  anubis-psql-db:
    image: postgres:14.1
    command: postgres -c 'max_connections=250'
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ../.env.template

  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ../.env.judge0.template:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    depends_on:
      workers:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_started

  workers:
    image: judge0/judge0:1.13.0
    command: [ "./scripts/workers" ]
    volumes:
      - ../.env.judge0.template:/judge0.conf:ro
    privileged: true
    restart: unless-stopped

  db:
    image: postgres:13.0
    env_file: ../.env.judge0.template
    restart: unless-stopped

  redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    ports:
      - "6379:6379"
    env_file: ../.env.judge0.template
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
    restart: unless-stopped
