global using FastEndpoints;
global using Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using FastEndpoints.Security;
global using Api;
global using FastEndpoints.Swagger;
global using Domain.Entities;
global using Application;
