name: Anubis - Build and Test Submissions Service

on:
  push:
    paths:
      - "anubis-eval/**"
      - ".github/workflows/anubis-eval-ci.yaml"

  pull_request:
    paths:
      - "anubis-eval/**"
      - ".github/workflows/anubis-eval-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: '1.72.0'

      - name: Build
        run: |
          cd anubis-eval
          cargo build --release

      - name: Test
        run: |
          cd anubis-eval
          cargo test --all-features
