name: Asgard Deployment - Deploy to DigitalOcean Droplet

on:
  push:
    branches:
        - master
        # - develop

  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #   - name: Log in to the Container registry
      #     uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #     with:
      #       registry: ${{ env.REGISTRY }}
      #       username: ${{ github.actor }}
      #       password: ${{ secrets.TOKEN }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy docker-compose.yaml to droplet
        run: sshpass -v -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no docker-compose.yaml root@${{ vars.DROPLET_IP }}:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd ~
            docker-compose --profile asgard down
            echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose --profile asgard pull
            docker-compose --profile asgard up -d
