name: Dapr - Build Docker image and publish to GHCR and Docker Hub

on:
  push:
    tags:
      - "dapr/**"

env:
  NAMESPACE: pantheonix
  REPOSITORY: asgard-dapr
  IMAGE_NAME: asgard-dapr-config
  BUILD_CONTEXT: dapr

jobs:
  deploy-to-ghcr:
    uses: ./.github/workflows/step-deploy-to-ghcr.yaml
    with:
      image_name: ${{ env.IMAGE_NAME }}
      build_context: ${{ env.BUILD_CONTEXT }}

  deploy-to-docker-hub:
    uses: ./.github/workflows/step-deploy-to-docker-hub.yaml
    with:
      namespace: ${{ env.NAMESPACE }}
      repository: ${{ env.REPOSITORY }}
      build_context: ${{ env.BUILD_CONTEXT }}