name: Dapr - Build Docker image and publish to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

#    branches:
#      - develop

    paths:
      - "dapr/**"
      - ".github/workflows/dapr-config.yaml"

  pull_request:
    branches:
      - develop

    paths:
      - "dapr-config/**"
      - ".github/workflows/dapr-config.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: asgard-dapr-config

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: dapr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
