name: Enki - Build Docker image and publish to GHCR and Docker Hub

on:
  push:
    tags:
      - "enki/**"

env:
  NAMESPACE: pantheonix
  REPOSITORY: enki
  IMAGE_NAME: enki-problems
  BUILD_CONTEXT: enki-problems

jobs:
  build:
    name: Build and Test Enki Problems Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enki-problems

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: |
          dotnet restore "src/EnkiProblems.HttpApi.Host/EnkiProblems.HttpApi.Host.csproj"
          dotnet restore "test/EnkiProblems.Application.Tests/EnkiProblems.Application.Tests.csproj"
          dotnet build --no-restore
      - name: Test
        run: dotnet test -e DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

  deploy_to_ghcr:
    needs: build
    uses: ./.github/workflows/step-deploy-to-ghcr.yaml
    with:
      image_name: ${{ env.IMAGE_NAME }}
      build_context: ${{ env.BUILD_CONTEXT }}

  deploy_to_docker_hub:
    needs: build
    uses: ./.github/workflows/step-deploy-to-docker-hub.yaml
    with:
      namespace: ${{ env.NAMESPACE }}
      repository: ${{ env.REPOSITORY }}
      build_context: ${{ env.BUILD_CONTEXT }}
