name: Eval Nginx Load Balancer - Build Docker image and publish to GitHub Packages

on:
  push:
    branches:
      - develop

    paths:
      - "anubis-eval/eval-lb/**"
      - ".github/workflows/eval-lb.yaml"

  pull_request:
    branches:
      - develop

    paths:
      - "anubis-eval/eval-lb/**"
      - ".github/workflows/eval-lb.yaml"

env:
  NAMESPACE: pantheonix
  REPOSITORY: eval-lb

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.NAMESPACE }}/${{ env.REPOSITORY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: anubis-eval/eval-lb
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
