name: Hermes - Build and Test Tests Service

on:
  push:
    paths:
      - "hermes-tests/**"
      - ".github/workflows/hermes-tests-ci.yaml"

  pull_request:
    paths:
      - "hermes-tests/**"
      - ".github/workflows/hermes-tests-ci.yaml"

env:
  HERMES_CONFIG: ${{ secrets.HERMES_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.2

      - name: Create logs/test.log file
        run: |
          mkdir -p hermes-tests/logs
          touch hermes-tests/logs/test.log

      - name: Get dependencies
        run: |
          cd hermes-tests
          dart pub get

      - name: Test
        run: |
          cd hermes-tests
          dart test
