name: Hermes - Build Docker image and publish to GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

#    branches:
#      - develop

    paths:
      - "hermes-tests/**"
      - ".github/workflows/hermes-tests-cd.yaml"

#  pull_request:
#    branches:
#      - develop
#
#    paths:
#      - "hermes-tests/**"
#      - ".github/workflows/hermes-tests-cd.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hermes-tests
  HERMES_CONFIG: ${{ secrets.HERMES_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hermes-tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.2

      - name: Create logs/test.log file
        run: |
          mkdir -p logs
          touch logs/test.log

      - name: Get dependencies
        run: dart pub get

      - name: Test
        run: dart test

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: hermes-tests
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
