name: Hermes - Build Docker image and publish to GitHub Packages

on:
  push:
    branches:
      - ucv

    paths:
      - "hermes-tests/**"
      - ".github/workflows/hermes-tests.yaml"

  pull_request:
    branches:
      - ucv

    paths:
      - "hermes-tests/**"
      - ".github/workflows/hermes-tests.yaml"

env:
  NAMESPACE: pantheonix
  REPOSITORY: hermes

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.NAMESPACE }}/${{ env.REPOSITORY }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ../../hermes-tests
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
