name: Odin - Build Docker image and publish to GHCR and Docker Hub

on:
  push:
    tags:
      - "odin/**"

jobs:
  deploy-to-ghcr:
    uses: ./.github/workflows/step-deploy-to-ghcr.yaml
    with:
      image_name: odin-api-gateway
      build_context: odin-gateway

  deploy-to-docker-hub:
    uses: ./.github/workflows/step-deploy-to-docker-hub.yaml
    with:
      namespace: pantheonix
      repository: odin
      build_context: odin-gateway

