name: Quetzalcoatl - Build Docker image and publish to GHCR and Docker Hub

on:
  push:
    tags:
      - "quetzalcoatl/**"

env:
  NAMESPACE: pantheonix
  REPOSITORY: quetzalcoatl
  IMAGE_NAME: quetzalcoatl-auth
  BUILD_CONTEXT: quetzalcoatl-auth

jobs:
  build:
    name: Build and Test Quetzalcoatl Auth Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quetzalcoatl-auth

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: |
          dotnet restore "Bootstrapper/Bootstrapper.csproj"
          dotnet restore "Tests.Integration/Tests.Integration.csproj"
          dotnet build --no-restore
      - name: Test
        run: dotnet test -e ASPNETCORE_ENVIRONMENT=Testing "Tests.Integration/Tests.Integration.csproj"

  deploy_to_ghcr:
    needs: build
    uses: ./.github/workflows/step-deploy-to-ghcr.yaml
    with:
      image_name: ${{ env.IMAGE_NAME }}
      build_context: ${{ env.BUILD_CONTEXT }}

  deploy_to_docker_hub:
    needs: build
    uses: ./.github/workflows/step-deploy-to-docker-hub.yaml
    with:
      namespace: ${{ env.NAMESPACE }}
      repository: ${{ env.REPOSITORY }}
      build_context: ${{ env.BUILD_CONTEXT }}
