name: Quetzalcoatl - Build Docker image and publish to GHCR and Docker Hub

on:
  push:
    tags:
      - "quetzalcoatl/**"

jobs:
  build:
    name: Build and Test Quetzalcoatl Auth Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quetzalcoatl-auth

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: |
          dotnet restore "Bootstrapper/Bootstrapper.csproj"
          dotnet restore "Tests.Integration/Tests.Integration.csproj"
          dotnet build --no-restore
#      - name: Test
#        run: dotnet test -e ASPNETCORE_ENVIRONMENT=Testing "Tests.Integration/Tests.Integration.csproj"

  deploy-to-ghcr:
    needs: build
    uses: ./.github/workflows/step-deploy-to-ghcr.yaml
    with:
      image_name: quetzalcoatl-auth
      build_context: quetzalcoatl-auth

  deploy-to-docker-hub:
    needs: build
    uses: ./.github/workflows/step-deploy-to-docker-hub.yaml
    with:
      namespace: pantheonix
      repository: quetzalcoatl
      build_context: quetzalcoatl-auth
