name: Quetzalcoatl - PR Verify

on:
  pull_request:
    branches:
      - develop
    paths:
      - "quetzalcoatl-auth/**"
      - ".github/workflows/quetzalcoatl-auth-pr-verify.yaml"

jobs:
  build:
    name: Build and Test Quetzalcoatl Auth Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quetzalcoatl-auth

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: |
          dotnet restore "Bootstrapper/Bootstrapper.csproj"
          dotnet restore "Tests.Integration/Tests.Integration.csproj"
          dotnet build --no-restore
      - name: Test
        run: dotnet test -e ASPNETCORE_ENVIRONMENT=Testing "Tests.Integration/Tests.Integration.csproj"