name: Quetzalcoatl - Build and Test Auth Service

on:
  push:
    paths:
        - "quetzalcoatl-auth/**"
        - ".github/workflows/quetzalcoatl-auth-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: |
          dotnet restore "quetzalcoatl-auth/Bootstrapper/Bootstrapper.csproj"
          dotnet restore "quetzalcoatl-auth/Tests.Integration/Tests.Integration.csproj"
          cd quetzalcoatl-auth
          dotnet build --no-restore
      - name: Test
        run: dotnet test -e ASPNETCORE_ENVIRONMENT=Testing "quetzalcoatl-auth/Tests.Integration/Tests.Integration.csproj"