name: "Step - Push Docker image to Docker Hub Registry"

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
      repository:
        type: string
        required: true
      build_context:
        type: string
        required: true

jobs:
  deploy:
    name: "Deploy to Docker Hub"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.namespace }}/${{ inputs.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.build_context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
